// Generated by CoffeeScript 1.7.1
require(["router", "navbar", "door"], function(router, navbar, door) {
  window.App = {};
  App.Views = {};
  App.Views.router = new router;
  App.Views.navbar = new navbar;
  return Backbone.history.start();
});
