// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["modals/login_modal"], function(login_modal) {
  var navbar;
  return navbar = (function(_super) {
    __extends(navbar, _super);

    function navbar() {
      this.dereg_user = __bind(this.dereg_user, this);
      this.reg_user = __bind(this.reg_user, this);
      return navbar.__super__.constructor.apply(this, arguments);
    }

    navbar.prototype.el = "#navbar";

    navbar.prototype.events = {
      "click #login-btn": "show_login_modal",
      "click .reg-user": "reg_user",
      "click .dereg-user": "dereg_user"
    };

    navbar.prototype.show_login_modal = function() {
      return new login_modal().render();
    };

    navbar.prototype.reg_user = function() {
      if (App.Views.mainView.is_authed() === false) {
        return this.show_login_modal();
      }
    };

    navbar.prototype.dereg_user = function() {
      if (App.Views.mainView.is_authed() === false) {
        return this.show_login_modal();
      }
    };

    navbar.prototype.show_creds = function(creds) {
      return $("#login-btn").innerText = "Logged in as " + creds.user;
    };

    return navbar;

  })(Backbone.View);
});
