// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["door"], function(door) {
  var router;
  return router = (function(_super) {
    __extends(router, _super);

    function router() {
      return router.__super__.constructor.apply(this, arguments);
    }

    router.prototype.routes = {
      "": "main_route"
    };

    router.prototype.main_route = function(param) {
      if (App.Views.mainView == null) {
        App.Views.mainView = new door;
        return App.Views.mainView.render();
      }
    };

    return router;

  })(Backbone.Router);
});
