// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(function() {
  return this.error_modal = (function(_super) {
    __extends(error_modal, _super);

    function error_modal() {
      this.ok = __bind(this.ok, this);
      this.render = __bind(this.render, this);
      return error_modal.__super__.constructor.apply(this, arguments);
    }

    error_modal.prototype.el = "#error-modal";

    error_modal.prototype.events = {
      "click #btn-ok": "ok"
    };

    error_modal.prototype.initialize = function(opts) {
      this.$okBtn = this.$el.find("#btn-ok");
      return $(document).on("keyup checkout", (function(_this) {
        return function(e) {
          if (e.keyCode === 13) {
            e.preventDefault();
            _this.ok();
          }
          if (e.keyCode === 27) {
            e.preventDefault();
            return _this.cancel();
          }
        };
      })(this));
    };

    error_modal.prototype.render = function(e) {
      this.$el.modal();
      return this;
    };

    error_modal.prototype.ok = function() {
      return this.cleanup();
    };

    error_modal.prototype.cleanup = function() {
      $(document).off("keyup checkout");
      this.$el.off("click", "#btn-ok");
      return this.$el.modal("hide");
    };

    return error_modal;

  })(Backbone.View);
});
