PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users (
user TEXT NOT NULL,
hash TEXT NOT NULL,
card_desc TEXT NOT NULL,
reg_date TEXT NOT NULL,
registrar TEXT NOT NULL
);
CREATE TABLE admins (
user TEXT NOT NULL,
salt TEXT NOT NULL,
hash TEXT NOT NULL,
reg_date TEXT NOT NULL
);
CREATE TABLE swipes (
swipe_date TEXT NOT NULL,
hash TEXT NOT NULL,
granted TEXT NOT NULL,
user TEXT NOT NULL
);
CREATE TABLE door (
id INTEGER PRIMARY KEY AUTOINCREMENT,
state INT NOT NULL,
timestamp TEXT NOT NULL
);
COMMIT;
